// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDthiwn9bg3_njDt5lxo2CeFQ2B7BVfv6g',
    appId: '1:1078074927913:android:a70ccb84ad4fde7c26e538',
    messagingSenderId: '1078074927913',
    projectId: 'book-summary-app-4e3b3',
    storageBucket: 'book-summary-app-4e3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMb7IYVWsygmRJVkwVWLTicWi9AhdcaM',
    appId: '1:1078074927913:ios:9c3e1ca5ad362a0d26e538',
    messagingSenderId: '1078074927913',
    projectId: 'book-summary-app-4e3b3',
    storageBucket: 'book-summary-app-4e3b3.appspot.com',
    iosClientId: '1078074927913-5mqo65ljfl0a22gdb6kkhk6c06gdinaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookSummary',
  );
}